### ISSUE TITLE
Adding a setup.py for VisualPIC

### ISSUE THREAD

**Issue by RemiLehe** [AngelFP/VisualPIC#8]
Right now, when using VisualPIC, the user needs to:
- install the dependencies by hand (using `pip`)
- navigate to the VisualPIC folder and execute the `__main__.py`

Both these two steps could be made more "flowy" by adding a `setup.py`. In this case:
- If the dependencies are indicated in `setup.py`, then they will be automatically checked, downloaded and installed when doing `python setup.py install`.
- The `setup.py` can also automatically add a command-line executable in your standard `$PATH` (e.g. `visualpic`) that can point to the `__main__.py`: see for instance the field `entry_point` in this example: https://github.com/openPMD/openPMD-validator/blob/1.1.X/setup.py

Thus I was wondering if there are any plans to add a `setup.py` for VisualPIC?

**Comment by AngelFP** [comment]
Hi Remi, thanks a lot for the suggestion. This is something that would definitely be interesting to add.

I will look into it once I have some time, but I'm not sure when that will be. I'm currently focusing on adding more features and polishing the 3D visualizer, but since I should really start thinking on doing some more physics and writing my thesis I'll probably have to leave visualpic aside for some time :/

Contributions are always welcome though ;)

**Comment by RemiLehe** [comment]
Sounds good. I just created a branch that contains the `setup.py`. This partially automatizes the installation process ; however, in its present state, it cannot automatically copy the custom `QVTKRenderWIndowInterator.py`. 

I am really not familiar with `vtk` and interactive GUI, but is there a way to do this differently (i.e. to *not* need to copy this custom file, and instead have some way to point to it in its current location inside `VisualPIC`) ?

**Comment by AngelFP** [comment]
Thanks for looking into it! I have been working on the custom files today and I managed to include them directly in the code, so that VisualPIC now imports the custom modules instead of the ones in the python library. 

I have just made PR from dev to master which also includes these changes, so you can check it out to work on the setup file.

**Comment by RemiLehe** [comment]
Thanks! I was able to successfully use my setup.py, starting from the updated master branch. You can have a look at the corresponding PR.
